### ISSUE TITLE
Feedback Rollup: v0.9.0-rc2

### ISSUE THREAD

**Issue by LarsKemmann** [countincognito/Zametek.ProjectPlan#69]
Here's my overall feedback from testing this release, with links to individual issues:

- Compilation/editing feels noticeably faster! 🚀
- The updated Dark color scheme is much nicer. It looks quite professional now. 😊
- #55 is great (I know you fixed that pre-beta.1 but just wanted to call it out).
- #52 works well. Making the Settings persist with the profile is a big improvement.
- #58 works well.
- #59 is indeed much more intuitive with the revised Dark colors.
- #51 works well; I think that can be closed.
- #49 works well; I think that can be closed.

Some high-priority issues that I'd love to see addressed next (for beta.2?):
- [x] #63 is still broken (I finally figured out how to reproduce it).
- [x] #61 still trips me up quite a bit. Is this an easy fix that can be prioritized?
- [x] I'd still really like to see #64 reopened and fixed soon. It's a little thing but becomes a significant annoyance with everyday use (and I frequently have multiple file versions open that I'm comparing between).

Several issues feel like they're worth addressing prior to a V1 release:
- [x] #67
- [x] #66 would be good to address before V1 to make the Dark color scheme consistent.
- [x] ~~For extra polish, #68 would address the window title bar being white on Windows (at least Windows 10, haven't tested on Win11) and make it follow the Dark theme~~ -- works fine in Win11, good enough. 😊

**Comment by LarsKemmann** [comment]
One more pre-V1 item to consider:
- #72

**Comment by countincognito** [comment]
#61 should be working since 0.9.0-beta - I will update the release notes.

**Comment by LarsKemmann** [comment]
I updated my original post and my comment to reflect #61 as well as #66 working correctly. The only critical open items I see are:
- #71
- #72 (could be merged into #7)

If "critical" extends to "things that will trip people up", #46 should also be on the list, and possibly #18 (which I admittedly haven't really played around with, but maybe because I had seen that issue and figured it wasn't worth the hassle to try something that wouldn't persist).

**Comment by LarsKemmann** [comment]
#73 is another (seemingly) small nice-to-have/quality-of-life improvement that might be nice to fit into the first official release.

**Comment by LarsKemmann** [comment]
@countincognito I think everything here is done aside from the Windows Installer/support for Windows Store! 👏🏻🚀

Don't think I'm done submitting feature ideas. 😁 And I'm going to mention as nice-to-haves some items that I would *love* to see implemented:
- #70 
- #74 
- #75 

But per your request for the beta/RC phase, if the goal was only to polish existing features, then you've gone above and beyond.

**Comment by LarsKemmann** [comment]
Actually, I think I should reopen this to highlight one remaining "sharp edge" that is worth addressing before V1. I haven't personally used the column reordering feature, but I think that's just because I knew from reading through all the issues that column order isn't currently being saved with the project plan file:
- [ ] #18

**Comment by countincognito** [comment]
All items now available in [v0.9.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.9.0) (except #18)
